#!/bin/sh

[ -z "$GTKDIALOG" ] && GTKDIALOG=gdlg2

MAIN_DIALOG='
<window title="Embedded GTK2 file chooser" width-request="720" height-request="520">
	<vbox border-width="10" spacing="8">
		<text>
			<label>Select an existing text file and activate it to print its path.</label>
		</text>
		<chooser default-file="/etc/hosts"
			fs-filters-mime="text/plain" fs-filters="*.txt|*.md">
			<default>/etc</default>
			<variable>SELECTED_FILE</variable>
			<action>echo "Selected: $SELECTED_FILE"</action>
			<action signal="selection-changed">echo "Current: $SELECTED_FILE"</action>
		</chooser>
		<hbuttonbox layout-style="end">
			<button>
				<label>Clear selection</label>
				<action function="clear">SELECTED_FILE</action>
			</button>
			<button ok></button>
			<button cancel></button>
		</hbuttonbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) printf '%s\n' "$MAIN_DIALOG" ;;
	*) "$GTKDIALOG" --program=MAIN_DIALOG ;;
esac
