#!/bin/sh

[ -z "$GTKDIALOG" ] && GTKDIALOG=gtkdialog

completion_file=$(mktemp "${TMPDIR:-/tmp}/gtkdialog-completion.XXXXXX") || exit 1
trap 'rm -f "$completion_file"' EXIT HUP INT TERM
printf '%s\n' Documentation Distribution > "$completion_file"

MAIN_DIALOG='
<window title="Native GTK2 entry completion" width-request="420">
	<vbox border-width="10" spacing="8">
		<text><label>Start typing a category, then choose a suggestion:</label></text>
		<entry completion="true" completion-minimum-key-length="1">
			<item>Development</item>
			<item>Design</item>
			<input completion="true">printf "%s\n" Deployment Debugging</input>
			<input file completion="true">'"$completion_file"'</input>
			<variable>CATEGORY</variable>
		</entry>
		<hbuttonbox>
			<button ok></button>
			<button cancel></button>
		</hbuttonbox>
	</vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) printf '%s\n' "$MAIN_DIALOG" ;;
	*) "$GTKDIALOG" --program=MAIN_DIALOG ;;
esac
