#!/bin/sh

[ -z "$GTKDIALOG" ] && GTKDIALOG=gtkdialog

export BAR_DIALOG='
<window>
	<vbox>
		<frame Progress>
			<text>
				<label>Some text describing what is happening.</label>
			</text>
			<progressbar>
				<variable>PROGRESS_BAR</variable>
				<label>Some Text</label>
				<input>i=0; while [ "$i" -le 10000 ]; do echo $((i / 100)); if [ "$i" -le 3000 ]; then echo "Start..."; elif [ "$i" -le 6000 ]; then echo "Middle..."; else echo "End..."; fi; i=$((i + 1)); done</input>
				<action function="refresh">ENTRY</action>
				<action function="closewindow">BAR_DIALOG</action>
				<action>echo ready</action>
			</progressbar>
		</frame>
		<hbox>
			<button cancel>
				<action function="closewindow">BAR_DIALOG</action>
			</button>
		</hbox>
	</vbox>
	<variable>BAR_DIALOG</variable>
</window>
'

export MAIN_DIALOG='
<window>
	<vbox>
		<entry>
			<variable>ENTRY</variable>
			<input>date</input>
		</entry>
		<hbox>
			<button cancel></button>
			<button>
				<label>Launch</label>
				<action function="launch">BAR_DIALOG</action>
			</button>
			<button>
				<label>Close</label>
				<action function="exit">CLOSE</action>
			</button>
		</hbox>
	</vbox>
</window>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" "$BAR_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
