#!/bin/sh

[ -z "$GTKDIALOG" ] && GTKDIALOG=gtkdialog

export BAR_DIALOG='
<window>
	<vbox>
		<frame Progress>
			<text>
				<label>Some text describing what is happening.</label>
			</text>
			<progressbar>
				<label>Some Text</label>
				<input>i=0; while [ "$i" -le 100 ]; do echo "$i"; if [ "$i" -le 30 ]; then echo "Start..."; elif [ "$i" -le 60 ]; then echo "Middle..."; else echo "End..."; fi; sleep 0.3; i=$((i + 10)); done</input>
				<action function="closewindow">BAR_DIALOG</action>
			</progressbar>
		</frame>
		<hbox>
			<button cancel>
				<action function="closewindow">BAR_DIALOG</action>
			</button>
		</hbox>
	</vbox>
	<variable>BAR_DIALOG</variable>
</window>
'

export MAIN_DIALOG='
<window>
	<hbox>
		<button cancel></button>
		<button>
			<label>Launch</label>
			<action function="launch">BAR_DIALOG</action>
		</button>
	</hbox>
</window>
'

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" "$BAR_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
