#!/bin/sh

[ -z "$GTKDIALOG" ] && GTKDIALOG=gtkdialog

MAIN_DIALOG='
<window title="Alignment" width-request="420" height-request="240">
	<alignment xalign="0.5" yalign="0.5" xscale="0" yscale="0"
		top-padding="16" bottom-padding="16"
		left-padding="24" right-padding="24">
		<frame>
			<vbox>
				<text><label>This group remains centred.</label></text>
				<button ok></button>
			</vbox>
			<label>GtkAlignment</label>
		</frame>
		<variable>ALIGNED_AREA</variable>
	</alignment>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) printf '%s\n' "$MAIN_DIALOG" ;;
	*) "$GTKDIALOG" --program=MAIN_DIALOG ;;
esac
